### ISSUE TITLE
error with alfred 4

### ISSUE THREAD

**Issue by syphar** [patrickkahl/alfred-tyme#4]
first of all: thanks for building this! This really could be a heavy productivity increase for me. 

Secondly: 
I wanted to setup this workflow for alfred 4, but it didn't work. 

What's missing? 

The error I'm getting: 
```
TypeError: Cannot read property 'filter' of undefined
    at Object.alfy.matches (/usr/local/lib/node_modules/alfred-tyme/node_modules/alfy/index.js:48:14)
    at Object.handler.getTasks (/usr/local/lib/node_modules/alfred-tyme/handler.js:8:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/alfred-tyme/index.js:15:18)
``` 

I'm happy to help where I can.

**Comment by syphar** [comment]
My mistake ... I didn't run the "init" part.
